name: Build & Publish Site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Generate site
        run: python generate.py
      - name: Commit generated site to docs/
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated site
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          file_pattern: "docs"
